### ISSUE TITLE
Please god WHY?

### ISSUE THREAD

**Issue by sewnie** [DaxGoon/avoidance#3]
Why is your script so poorly written but you still decide to use `main` and `printf`?

https://github.com/DaxGoon/avoidance/blob/8b6b2dc7e143cafe49ec11a7509096e21849544e/avoidance-start.sh#L36-L74

This entire area is absolute shit.
Why not just use something so much cleaner like

https://github.com/wael444/avoidance/blob/601813c96f36b5e9213ba882d187384da0f2fef8/avoidance-start.sh#L21-L49

And besides, its much more relevant to make this script for _advanced_ users who know what they want and what they are doing, So this entire section can be removed and can just be easier to allow whatever the fuck is in `pkg_file`.

Insights:
+ Why a single if statement for EVERYTHING? 
+ This entire script is hardcoded to `wpa_supplicant`. cannot use some alternative like `iwd`.
+ allowing `void-packages` to also be hardcoded. you should NOT use `cd` in a script like this. it should be 100% optional to set this up by the user, This thing will take up major space.
+ Installing each package ONE by ONE. **NO!**
+ hard coding `elogind`. 
+ hard coding `grub`.
+ using `sudo`.
+ hard coding `polybar` if using `bspwm` as the """DE""" when it's a damn window manager!
+ hard coding touch pad settings.
+ using emojis in the done script.
+ Why use separate `resolve`_* scripts?? What for??

I could rewrite this entire script in a at the minimum much more acceptable/annoying style. Only if you want me to, Hell i'd rather just redo this entire projects idea and just add it as an extension to the already existing `void-installer`.

https://github.com/DaxGoon/avoidance#contributing-guidelines
Seriously?? Nah.

**Comment by DaxGoon** [comment]
Hi,
Thanks for the feedback. Would you like to create a PR with the changes you suggested?

—
